name: TypeBetter
options:
  bundleIdPrefix: com.typebetter
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.0.0"

settings:
  SWIFT_VERSION: "5.9"
  MACOSX_DEPLOYMENT_TARGET: "13.0"
  ARCHS: arm64

targets:
  TypeBetter:
    type: application
    platform: macOS
    sources:
      - TypeBetter
    dependencies:
      - package: Sparkle
    settings:
      PRODUCT_NAME: TypeBetter
      PRODUCT_BUNDLE_IDENTIFIER: com.typebetter.app
      INFOPLIST_FILE: TypeBetter/Info.plist
      CODE_SIGN_ENTITLEMENTS: TypeBetter/TypeBetter.entitlements
      LD_RUNPATH_SEARCH_PATHS:
        - $(inherited)
        - "@executable_path/../Frameworks"

      # === CODE SIGNING (Direct Download / Notarized) ===
      DEVELOPMENT_TEAM: "7MKQAN7HM5"
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "Apple Development"

      # Required for notarization
      ENABLE_HARDENED_RUNTIME: YES

    info:
      path: TypeBetter/Info.plist
      properties:
        LSUIElement: true
        CFBundleShortVersionString: "1.4"
        CFBundleVersion: "5"
        NSHumanReadableCopyright: "Copyright © 2026 TypeBetter. All rights reserved."
